[package]
name = "armx64"
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
description = "A high-performance AArch64 to x86-64 dynamic translation engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/2moresym/ARMx64"

[dependencies]
rayon = "1.12"
yaxpeax-arm = "0.4"
yaxpeax-arch = "0.3"
memmap2 = "0.9"
hashbrown = "0.16"
smallvec = "1.15"
object = "0.37"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
